# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlador.ui'
#
# Created: Mon Mar 27 12:04:54 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1045)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sliderObservados = QtGui.QFrame(self.centralwidget)
        self.sliderObservados.setGeometry(QtCore.QRect(420, 590, 851, 171))
        self.sliderObservados.setFrameShape(QtGui.QFrame.Box)
        self.sliderObservados.setFrameShadow(QtGui.QFrame.Raised)
        self.sliderObservados.setObjectName("sliderObservados")
        self.fechaSlider = QtGui.QSlider(self.sliderObservados)
        self.fechaSlider.setGeometry(QtCore.QRect(40, 80, 771, 41))
        self.fechaSlider.setMinimum(1)
        self.fechaSlider.setMaximum(51)
        self.fechaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fechaSlider.setObjectName("fechaSlider")
        self.label_7 = QtGui.QLabel(self.sliderObservados)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.controlesVideo = QtGui.QFrame(self.centralwidget)
        self.controlesVideo.setGeometry(QtCore.QRect(860, 820, 411, 161))
        self.controlesVideo.setFrameShape(QtGui.QFrame.Box)
        self.controlesVideo.setFrameShadow(QtGui.QFrame.Raised)
        self.controlesVideo.setObjectName("controlesVideo")
        self.play = QtGui.QPushButton(self.controlesVideo)
        self.play.setGeometry(QtCore.QRect(20, 90, 75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.play.setFont(font)
        self.play.setObjectName("play")
        self.stop = QtGui.QPushButton(self.controlesVideo)
        self.stop.setGeometry(QtCore.QRect(110, 90, 75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stop.setFont(font)
        self.stop.setObjectName("stop")
        self.pause = QtGui.QPushButton(self.controlesVideo)
        self.pause.setGeometry(QtCore.QRect(200, 90, 75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pause.setFont(font)
        self.pause.setObjectName("pause")
        self.loop = QtGui.QCheckBox(self.controlesVideo)
        self.loop.setGeometry(QtCore.QRect(300, 90, 70, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loop.setFont(font)
        self.loop.setObjectName("loop")
        self.label_6 = QtGui.QLabel(self.controlesVideo)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(420, 340, 401, 191))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.vincularPorTiempo = QtGui.QPushButton(self.frame)
        self.vincularPorTiempo.setGeometry(QtCore.QRect(20, 50, 170, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vincularPorTiempo.setFont(font)
        self.vincularPorTiempo.setObjectName("vincularPorTiempo")
        self.vincularPorEspacio = QtGui.QPushButton(self.frame)
        self.vincularPorEspacio.setGeometry(QtCore.QRect(210, 50, 170, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vincularPorEspacio.setFont(font)
        self.vincularPorEspacio.setObjectName("vincularPorEspacio")
        self.desvincularTiempo = QtGui.QPushButton(self.frame)
        self.desvincularTiempo.setGeometry(QtCore.QRect(20, 140, 170, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.desvincularTiempo.setFont(font)
        self.desvincularTiempo.setObjectName("desvincularTiempo")
        self.hermanasDeTiempo = QtGui.QLineEdit(self.frame)
        self.hermanasDeTiempo.setGeometry(QtCore.QRect(20, 96, 170, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hermanasDeTiempo.setFont(font)
        self.hermanasDeTiempo.setObjectName("hermanasDeTiempo")
        self.hermanasDeEspacio = QtGui.QLineEdit(self.frame)
        self.hermanasDeEspacio.setGeometry(QtCore.QRect(210, 96, 170, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hermanasDeEspacio.setFont(font)
        self.hermanasDeEspacio.setObjectName("hermanasDeEspacio")
        self.desvincularEspacio = QtGui.QPushButton(self.frame)
        self.desvincularEspacio.setGeometry(QtCore.QRect(210, 140, 170, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.desvincularEspacio.setFont(font)
        self.desvincularEspacio.setObjectName("desvincularEspacio")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(420, 130, 1351, 171))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.x1 = QtGui.QPushButton(self.frame_3)
        self.x1.setGeometry(QtCore.QRect(150, 10, 40, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x1.setFont(font)
        self.x1.setObjectName("x1")
        self.x2 = QtGui.QPushButton(self.frame_3)
        self.x2.setGeometry(QtCore.QRect(200, 10, 40, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x2.setFont(font)
        self.x2.setObjectName("x2")
        self.x3 = QtGui.QPushButton(self.frame_3)
        self.x3.setGeometry(QtCore.QRect(250, 10, 40, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x3.setFont(font)
        self.x3.setObjectName("x3")
        self.x4 = QtGui.QPushButton(self.frame_3)
        self.x4.setGeometry(QtCore.QRect(300, 10, 40, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x4.setFont(font)
        self.x4.setObjectName("x4")
        self.splitter_2 = QtGui.QSplitter(self.frame_3)
        self.splitter_2.setGeometry(QtCore.QRect(20, 60, 1311, 91))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.P1 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P1.setFont(font)
        self.P1.setCheckable(True)
        self.P1.setAutoExclusive(True)
        self.P1.setObjectName("P1")
        self.P2 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P2.setFont(font)
        self.P2.setCheckable(True)
        self.P2.setAutoExclusive(True)
        self.P2.setObjectName("P2")
        self.P3 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P3.setFont(font)
        self.P3.setCheckable(True)
        self.P3.setAutoExclusive(True)
        self.P3.setObjectName("P3")
        self.P4 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P4.setFont(font)
        self.P4.setCheckable(True)
        self.P4.setAutoExclusive(True)
        self.P4.setObjectName("P4")
        self.P5 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P5.setFont(font)
        self.P5.setCheckable(True)
        self.P5.setAutoExclusive(True)
        self.P5.setObjectName("P5")
        self.P6 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P6.setFont(font)
        self.P6.setCheckable(True)
        self.P6.setAutoExclusive(True)
        self.P6.setObjectName("P6")
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(860, 340, 411, 191))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtGui.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.addWeb = QtGui.QPushButton(self.frame_4)
        self.addWeb.setGeometry(QtCore.QRect(20, 140, 172, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addWeb.setFont(font)
        self.addWeb.setObjectName("addWeb")
        self.addSerie = QtGui.QPushButton(self.frame_4)
        self.addSerie.setGeometry(QtCore.QRect(20, 50, 172, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addSerie.setFont(font)
        self.addSerie.setObjectName("addSerie")
        self.addSerieWeb = QtGui.QPushButton(self.frame_4)
        self.addSerieWeb.setGeometry(QtCore.QRect(20, 96, 172, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addSerieWeb.setFont(font)
        self.addSerieWeb.setObjectName("addSerieWeb")
        self.addVideo = QtGui.QPushButton(self.frame_4)
        self.addVideo.setGeometry(QtCore.QRect(220, 96, 172, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addVideo.setFont(font)
        self.addVideo.setObjectName("addVideo")
        self.addImage = QtGui.QPushButton(self.frame_4)
        self.addImage.setGeometry(QtCore.QRect(220, 50, 172, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addImage.setFont(font)
        self.addImage.setObjectName("addImage")
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(1310, 340, 461, 641))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.guardaPantallas = QtGui.QPushButton(self.frame_5)
        self.guardaPantallas.setGeometry(QtCore.QRect(300, 50, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.guardaPantallas.setFont(font)
        self.guardaPantallas.setObjectName("guardaPantallas")
        self.listView = QtGui.QListView(self.frame_5)
        self.listView.setGeometry(QtCore.QRect(20, 50, 261, 571))
        self.listView.setDragEnabled(True)
        self.listView.setDragDropOverwriteMode(False)
        self.listView.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listView.setAlternatingRowColors(True)
        self.listView.setMovement(QtGui.QListView.Free)
        self.listView.setObjectName("listView")
        self.duplicar = QtGui.QPushButton(self.frame_5)
        self.duplicar.setGeometry(QtCore.QRect(300, 250, 141, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.duplicar.setFont(font)
        self.duplicar.setObjectName("duplicar")
        self.cargaGuion = QtGui.QPushButton(self.frame_5)
        self.cargaGuion.setGeometry(QtCore.QRect(300, 530, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cargaGuion.setFont(font)
        self.cargaGuion.setObjectName("cargaGuion")
        self.borrar = QtGui.QPushButton(self.frame_5)
        self.borrar.setGeometry(QtCore.QRect(300, 290, 141, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.borrar.setFont(font)
        self.borrar.setObjectName("borrar")
        self.playGuion = QtGui.QPushButton(self.frame_5)
        self.playGuion.setGeometry(QtCore.QRect(300, 330, 141, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.playGuion.setFont(font)
        self.playGuion.setObjectName("playGuion")
        self.stopGuion = QtGui.QPushButton(self.frame_5)
        self.stopGuion.setGeometry(QtCore.QRect(300, 370, 141, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stopGuion.setFont(font)
        self.stopGuion.setObjectName("stopGuion")
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.guardaGuion = QtGui.QPushButton(self.frame_5)
        self.guardaGuion.setGeometry(QtCore.QRect(300, 580, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.guardaGuion.setFont(font)
        self.guardaGuion.setObjectName("guardaGuion")
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(420, 820, 401, 161))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.fpSlider = QtGui.QSlider(self.frame_6)
        self.fpSlider.setGeometry(QtCore.QRect(20, 50, 351, 29))
        self.fpSlider.setMinimum(10)
        self.fpSlider.setMaximum(20)
        self.fpSlider.setPageStep(3)
        self.fpSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fpSlider.setObjectName("fpSlider")
        self.frame_2 = QtGui.QFrame(self.frame_6)
        self.frame_2.setGeometry(QtCore.QRect(20, 95, 351, 45))
        self.frame_2.setStyleSheet("background-color:lightgray")
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.c5 = QtGui.QLabel(self.frame_2)
        self.c5.setGeometry(QtCore.QRect(270, 10, 64, 24))
        self.c5.setAutoFillBackground(False)
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.c1 = QtGui.QLabel(self.frame_2)
        self.c1.setGeometry(QtCore.QRect(14, 10, 64, 24))
        self.c1.setAutoFillBackground(False)
        self.c1.setText("")
        self.c1.setObjectName("c1")
        self.c2 = QtGui.QLabel(self.frame_2)
        self.c2.setGeometry(QtCore.QRect(78, 10, 64, 24))
        self.c2.setAutoFillBackground(False)
        self.c2.setText("")
        self.c2.setObjectName("c2")
        self.c3 = QtGui.QLabel(self.frame_2)
        self.c3.setGeometry(QtCore.QRect(142, 10, 64, 24))
        self.c3.setAutoFillBackground(False)
        self.c3.setText("")
        self.c3.setObjectName("c3")
        self.c4 = QtGui.QLabel(self.frame_2)
        self.c4.setGeometry(QtCore.QRect(206, 10, 64, 24))
        self.c4.setAutoFillBackground(False)
        self.c4.setText("")
        self.c4.setObjectName("c4")
        self.label_5 = QtGui.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(420, 30, 1351, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(3, 78, 168);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame_7 = QtGui.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(90, 40, 231, 941))
        self.frame_7.setAutoFillBackground(False)
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.logos = QtGui.QLabel(self.frame_7)
        self.logos.setGeometry(QtCore.QRect(60, 0, 121, 941))
        self.logos.setText("")
        self.logos.setObjectName("logos")
        self.satellite = QtGui.QPushButton(self.centralwidget)
        self.satellite.setGeometry(QtCore.QRect(590, 550, 75, 23))
        self.satellite.setObjectName("satellite")
        self.calles = QtGui.QPushButton(self.centralwidget)
        self.calles.setGeometry(QtCore.QRect(680, 550, 75, 23))
        self.calles.setObjectName("calles")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tablero de control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Tiempo", None, QtGui.QApplication.UnicodeUTF8))
        self.play.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.loop.setText(QtGui.QApplication.translate("MainWindow", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Control de video", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Vincular pantallas:", None, QtGui.QApplication.UnicodeUTF8))
        self.vincularPorTiempo.setText(QtGui.QApplication.translate("MainWindow", "Por tiempo", None, QtGui.QApplication.UnicodeUTF8))
        self.vincularPorEspacio.setText(QtGui.QApplication.translate("MainWindow", "Por espacio", None, QtGui.QApplication.UnicodeUTF8))
        self.desvincularTiempo.setText(QtGui.QApplication.translate("MainWindow", "Desvincular", None, QtGui.QApplication.UnicodeUTF8))
        self.desvincularEspacio.setText(QtGui.QApplication.translate("MainWindow", "Desvincular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Pantallas", None, QtGui.QApplication.UnicodeUTF8))
        self.x1.setText(QtGui.QApplication.translate("MainWindow", "x1", None, QtGui.QApplication.UnicodeUTF8))
        self.x2.setText(QtGui.QApplication.translate("MainWindow", "x2", None, QtGui.QApplication.UnicodeUTF8))
        self.x3.setText(QtGui.QApplication.translate("MainWindow", "x3", None, QtGui.QApplication.UnicodeUTF8))
        self.x4.setText(QtGui.QApplication.translate("MainWindow", "x4", None, QtGui.QApplication.UnicodeUTF8))
        self.P1.setText(QtGui.QApplication.translate("MainWindow", "P1", None, QtGui.QApplication.UnicodeUTF8))
        self.P2.setText(QtGui.QApplication.translate("MainWindow", "P2", None, QtGui.QApplication.UnicodeUTF8))
        self.P3.setText(QtGui.QApplication.translate("MainWindow", "P3", None, QtGui.QApplication.UnicodeUTF8))
        self.P4.setText(QtGui.QApplication.translate("MainWindow", "P4", None, QtGui.QApplication.UnicodeUTF8))
        self.P5.setText(QtGui.QApplication.translate("MainWindow", "P5", None, QtGui.QApplication.UnicodeUTF8))
        self.P6.setText(QtGui.QApplication.translate("MainWindow", "P6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Agregar:", None, QtGui.QApplication.UnicodeUTF8))
        self.addWeb.setText(QtGui.QApplication.translate("MainWindow", "Página web", None, QtGui.QApplication.UnicodeUTF8))
        self.addSerie.setText(QtGui.QApplication.translate("MainWindow", "Serie de imágenes", None, QtGui.QApplication.UnicodeUTF8))
        self.addSerieWeb.setText(QtGui.QApplication.translate("MainWindow", "Serie web", None, QtGui.QApplication.UnicodeUTF8))
        self.addVideo.setText(QtGui.QApplication.translate("MainWindow", "Video", None, QtGui.QApplication.UnicodeUTF8))
        self.addImage.setText(QtGui.QApplication.translate("MainWindow", " Imagen", None, QtGui.QApplication.UnicodeUTF8))
        self.guardaPantallas.setText(QtGui.QApplication.translate("MainWindow", "Guarda \n"
"pantallas", None, QtGui.QApplication.UnicodeUTF8))
        self.duplicar.setText(QtGui.QApplication.translate("MainWindow", "Duplicar", None, QtGui.QApplication.UnicodeUTF8))
        self.cargaGuion.setText(QtGui.QApplication.translate("MainWindow", "Carga Guión", None, QtGui.QApplication.UnicodeUTF8))
        self.borrar.setText(QtGui.QApplication.translate("MainWindow", "Borrar", None, QtGui.QApplication.UnicodeUTF8))
        self.playGuion.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.stopGuion.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Guión", None, QtGui.QApplication.UnicodeUTF8))
        self.guardaGuion.setText(QtGui.QApplication.translate("MainWindow", "Guarda Guión", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Categorías", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Plataforma de Análisis de Vulnerabilidad en Megalópolis", None, QtGui.QApplication.UnicodeUTF8))
        self.satellite.setText(QtGui.QApplication.translate("MainWindow", "Satellite", None, QtGui.QApplication.UnicodeUTF8))
        self.calles.setText(QtGui.QApplication.translate("MainWindow", "Calles", None, QtGui.QApplication.UnicodeUTF8))

