# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlador.ui'
#
# Created: Sun Mar 19 02:19:03 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1735, 1000)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sliderObservados = QtGui.QFrame(self.centralwidget)
        self.sliderObservados.setGeometry(QtCore.QRect(380, 350, 631, 91))
        self.sliderObservados.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sliderObservados.setFrameShadow(QtGui.QFrame.Raised)
        self.sliderObservados.setObjectName("sliderObservados")
        self.fechaSlider = QtGui.QSlider(self.sliderObservados)
        self.fechaSlider.setGeometry(QtCore.QRect(60, 50, 541, 41))
        self.fechaSlider.setMinimum(1)
        self.fechaSlider.setMaximum(51)
        self.fechaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fechaSlider.setObjectName("fechaSlider")
        self.guardaPantallas = QtGui.QPushButton(self.centralwidget)
        self.guardaPantallas.setGeometry(QtCore.QRect(1350, 200, 141, 41))
        self.guardaPantallas.setObjectName("guardaPantallas")
        self.guardaGuion = QtGui.QPushButton(self.centralwidget)
        self.guardaGuion.setGeometry(QtCore.QRect(1310, 810, 121, 41))
        self.guardaGuion.setObjectName("guardaGuion")
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(1330, 300, 231, 481))
        self.listView.setDragEnabled(True)
        self.listView.setDragDropOverwriteMode(False)
        self.listView.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listView.setAlternatingRowColors(True)
        self.listView.setMovement(QtGui.QListView.Free)
        self.listView.setObjectName("listView")
        self.duplicar = QtGui.QPushButton(self.centralwidget)
        self.duplicar.setGeometry(QtCore.QRect(1610, 390, 75, 23))
        self.duplicar.setObjectName("duplicar")
        self.borrar = QtGui.QPushButton(self.centralwidget)
        self.borrar.setGeometry(QtCore.QRect(1610, 450, 75, 23))
        self.borrar.setObjectName("borrar")
        self.cargaGuion = QtGui.QPushButton(self.centralwidget)
        self.cargaGuion.setGeometry(QtCore.QRect(1460, 810, 121, 41))
        self.cargaGuion.setObjectName("cargaGuion")
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(40, 20, 1571, 131))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.P1 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P1.setFont(font)
        self.P1.setCheckable(True)
        self.P1.setAutoExclusive(True)
        self.P1.setObjectName("P1")
        self.P2 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P2.setFont(font)
        self.P2.setCheckable(True)
        self.P2.setAutoExclusive(True)
        self.P2.setObjectName("P2")
        self.P3 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P3.setFont(font)
        self.P3.setCheckable(True)
        self.P3.setAutoExclusive(True)
        self.P3.setObjectName("P3")
        self.P4 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P4.setFont(font)
        self.P4.setCheckable(True)
        self.P4.setAutoExclusive(True)
        self.P4.setObjectName("P4")
        self.P5 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P5.setFont(font)
        self.P5.setCheckable(True)
        self.P5.setAutoExclusive(True)
        self.P5.setObjectName("P5")
        self.P6 = QtGui.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.P6.setFont(font)
        self.P6.setCheckable(True)
        self.P6.setAutoExclusive(True)
        self.P6.setObjectName("P6")
        self.addImage = QtGui.QPushButton(self.centralwidget)
        self.addImage.setGeometry(QtCore.QRect(800, 190, 171, 23))
        self.addImage.setObjectName("addImage")
        self.addVideo = QtGui.QPushButton(self.centralwidget)
        self.addVideo.setGeometry(QtCore.QRect(800, 220, 171, 23))
        self.addVideo.setObjectName("addVideo")
        self.x2 = QtGui.QPushButton(self.centralwidget)
        self.x2.setGeometry(QtCore.QRect(1050, 200, 31, 23))
        self.x2.setObjectName("x2")
        self.x3 = QtGui.QPushButton(self.centralwidget)
        self.x3.setGeometry(QtCore.QRect(1090, 200, 31, 23))
        self.x3.setObjectName("x3")
        self.x4 = QtGui.QPushButton(self.centralwidget)
        self.x4.setGeometry(QtCore.QRect(1130, 200, 31, 23))
        self.x4.setObjectName("x4")
        self.x1 = QtGui.QPushButton(self.centralwidget)
        self.x1.setGeometry(QtCore.QRect(1010, 200, 31, 23))
        self.x1.setObjectName("x1")
        self.controlesVideo = QtGui.QFrame(self.centralwidget)
        self.controlesVideo.setGeometry(QtCore.QRect(520, 660, 561, 80))
        self.controlesVideo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.controlesVideo.setFrameShadow(QtGui.QFrame.Raised)
        self.controlesVideo.setObjectName("controlesVideo")
        self.play = QtGui.QPushButton(self.controlesVideo)
        self.play.setGeometry(QtCore.QRect(40, 50, 75, 23))
        self.play.setObjectName("play")
        self.stop = QtGui.QPushButton(self.controlesVideo)
        self.stop.setGeometry(QtCore.QRect(150, 50, 75, 23))
        self.stop.setObjectName("stop")
        self.pause = QtGui.QPushButton(self.controlesVideo)
        self.pause.setGeometry(QtCore.QRect(260, 50, 75, 23))
        self.pause.setObjectName("pause")
        self.loop = QtGui.QCheckBox(self.controlesVideo)
        self.loop.setGeometry(QtCore.QRect(380, 50, 70, 17))
        self.loop.setObjectName("loop")
        self.playGuion = QtGui.QPushButton(self.centralwidget)
        self.playGuion.setGeometry(QtCore.QRect(1610, 540, 75, 23))
        self.playGuion.setObjectName("playGuion")
        self.stopGuion = QtGui.QPushButton(self.centralwidget)
        self.stopGuion.setGeometry(QtCore.QRect(1610, 590, 75, 23))
        self.stopGuion.setObjectName("stopGuion")
        self.addSerie = QtGui.QPushButton(self.centralwidget)
        self.addSerie.setGeometry(QtCore.QRect(800, 250, 171, 23))
        self.addSerie.setObjectName("addSerie")
        self.addSerieWeb = QtGui.QPushButton(self.centralwidget)
        self.addSerieWeb.setGeometry(QtCore.QRect(800, 280, 171, 23))
        self.addSerieWeb.setObjectName("addSerieWeb")
        self.addWeb = QtGui.QPushButton(self.centralwidget)
        self.addWeb.setGeometry(QtCore.QRect(800, 310, 171, 23))
        self.addWeb.setObjectName("addWeb")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 170, 591, 171))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 10, 131, 20))
        self.label.setObjectName("label")
        self.vincularPorTiempo = QtGui.QPushButton(self.frame)
        self.vincularPorTiempo.setGeometry(QtCore.QRect(20, 40, 171, 27))
        self.vincularPorTiempo.setObjectName("vincularPorTiempo")
        self.vincularPorEspacio = QtGui.QPushButton(self.frame)
        self.vincularPorEspacio.setGeometry(QtCore.QRect(20, 80, 171, 27))
        self.vincularPorEspacio.setObjectName("vincularPorEspacio")
        self.desvincularTiempo = QtGui.QPushButton(self.frame)
        self.desvincularTiempo.setGeometry(QtCore.QRect(420, 40, 121, 27))
        self.desvincularTiempo.setObjectName("desvincularTiempo")
        self.hermanasDeTiempo = QtGui.QLineEdit(self.frame)
        self.hermanasDeTiempo.setGeometry(QtCore.QRect(220, 40, 171, 27))
        self.hermanasDeTiempo.setObjectName("hermanasDeTiempo")
        self.hermanasDeEspacio = QtGui.QLineEdit(self.frame)
        self.hermanasDeEspacio.setGeometry(QtCore.QRect(220, 80, 171, 27))
        self.hermanasDeEspacio.setObjectName("hermanasDeEspacio")
        self.desvincularEspacio = QtGui.QPushButton(self.frame)
        self.desvincularEspacio.setGeometry(QtCore.QRect(420, 80, 121, 27))
        self.desvincularEspacio.setObjectName("desvincularEspacio")
        self.fpSlider = QtGui.QSlider(self.centralwidget)
        self.fpSlider.setGeometry(QtCore.QRect(60, 390, 281, 29))
        self.fpSlider.setMinimum(10)
        self.fpSlider.setMaximum(20)
        self.fpSlider.setPageStep(3)
        self.fpSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fpSlider.setObjectName("fpSlider")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(50, 445, 321, 45))
        self.frame_2.setStyleSheet("background-color:lightgray")
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.c5 = QtGui.QLabel(self.frame_2)
        self.c5.setGeometry(QtCore.QRect(250, 10, 60, 24))
        self.c5.setAutoFillBackground(False)
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.c1 = QtGui.QLabel(self.frame_2)
        self.c1.setGeometry(QtCore.QRect(10, 10, 60, 24))
        self.c1.setAutoFillBackground(False)
        self.c1.setText("")
        self.c1.setObjectName("c1")
        self.c2 = QtGui.QLabel(self.frame_2)
        self.c2.setGeometry(QtCore.QRect(70, 10, 60, 24))
        self.c2.setAutoFillBackground(False)
        self.c2.setText("")
        self.c2.setObjectName("c2")
        self.c3 = QtGui.QLabel(self.frame_2)
        self.c3.setGeometry(QtCore.QRect(130, 10, 60, 24))
        self.c3.setAutoFillBackground(False)
        self.c3.setText("")
        self.c3.setObjectName("c3")
        self.c4 = QtGui.QLabel(self.frame_2)
        self.c4.setGeometry(QtCore.QRect(190, 10, 60, 24))
        self.c4.setAutoFillBackground(False)
        self.c4.setText("")
        self.c4.setObjectName("c4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1735, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.guardaPantallas.setText(QtGui.QApplication.translate("MainWindow", "Guarda pantallas", None, QtGui.QApplication.UnicodeUTF8))
        self.guardaGuion.setText(QtGui.QApplication.translate("MainWindow", "Guarda Guión", None, QtGui.QApplication.UnicodeUTF8))
        self.duplicar.setText(QtGui.QApplication.translate("MainWindow", "Duplicar", None, QtGui.QApplication.UnicodeUTF8))
        self.borrar.setText(QtGui.QApplication.translate("MainWindow", "Borrar", None, QtGui.QApplication.UnicodeUTF8))
        self.cargaGuion.setText(QtGui.QApplication.translate("MainWindow", "Carga Guión", None, QtGui.QApplication.UnicodeUTF8))
        self.P1.setText(QtGui.QApplication.translate("MainWindow", "P1", None, QtGui.QApplication.UnicodeUTF8))
        self.P2.setText(QtGui.QApplication.translate("MainWindow", "P2", None, QtGui.QApplication.UnicodeUTF8))
        self.P3.setText(QtGui.QApplication.translate("MainWindow", "P3", None, QtGui.QApplication.UnicodeUTF8))
        self.P4.setText(QtGui.QApplication.translate("MainWindow", "P4", None, QtGui.QApplication.UnicodeUTF8))
        self.P5.setText(QtGui.QApplication.translate("MainWindow", "P5", None, QtGui.QApplication.UnicodeUTF8))
        self.P6.setText(QtGui.QApplication.translate("MainWindow", "P6", None, QtGui.QApplication.UnicodeUTF8))
        self.addImage.setText(QtGui.QApplication.translate("MainWindow", "Agregar Imagen", None, QtGui.QApplication.UnicodeUTF8))
        self.addVideo.setText(QtGui.QApplication.translate("MainWindow", "Agregar Video", None, QtGui.QApplication.UnicodeUTF8))
        self.x2.setText(QtGui.QApplication.translate("MainWindow", "x2", None, QtGui.QApplication.UnicodeUTF8))
        self.x3.setText(QtGui.QApplication.translate("MainWindow", "x3", None, QtGui.QApplication.UnicodeUTF8))
        self.x4.setText(QtGui.QApplication.translate("MainWindow", "x4", None, QtGui.QApplication.UnicodeUTF8))
        self.x1.setText(QtGui.QApplication.translate("MainWindow", "x1", None, QtGui.QApplication.UnicodeUTF8))
        self.play.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.loop.setText(QtGui.QApplication.translate("MainWindow", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.playGuion.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.stopGuion.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.addSerie.setText(QtGui.QApplication.translate("MainWindow", "Agregar Serie", None, QtGui.QApplication.UnicodeUTF8))
        self.addSerieWeb.setText(QtGui.QApplication.translate("MainWindow", "Agregar Serie Web", None, QtGui.QApplication.UnicodeUTF8))
        self.addWeb.setText(QtGui.QApplication.translate("MainWindow", "Agregar Pagina Web", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Vincular Pantallas", None, QtGui.QApplication.UnicodeUTF8))
        self.vincularPorTiempo.setText(QtGui.QApplication.translate("MainWindow", "vincular por tiempo", None, QtGui.QApplication.UnicodeUTF8))
        self.vincularPorEspacio.setText(QtGui.QApplication.translate("MainWindow", "vincular por espacio", None, QtGui.QApplication.UnicodeUTF8))
        self.desvincularTiempo.setText(QtGui.QApplication.translate("MainWindow", "desvincular", None, QtGui.QApplication.UnicodeUTF8))
        self.desvincularEspacio.setText(QtGui.QApplication.translate("MainWindow", "desvincular", None, QtGui.QApplication.UnicodeUTF8))

