# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'controlador2.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1900, 1045)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sliderObservados = QFrame(self.centralwidget)
        self.sliderObservados.setObjectName(u"sliderObservados")
        self.sliderObservados.setGeometry(QRect(420, 590, 851, 171))
        self.sliderObservados.setFrameShape(QFrame.Box)
        self.sliderObservados.setFrameShadow(QFrame.Raised)
        self.fechaSlider = QSlider(self.sliderObservados)
        self.fechaSlider.setObjectName(u"fechaSlider")
        self.fechaSlider.setGeometry(QRect(40, 80, 771, 41))
        self.fechaSlider.setMinimum(1)
        self.fechaSlider.setMaximum(51)
        self.fechaSlider.setOrientation(Qt.Horizontal)
        self.label_7 = QLabel(self.sliderObservados)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 10, 91, 30))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.controlesVideo = QFrame(self.centralwidget)
        self.controlesVideo.setObjectName(u"controlesVideo")
        self.controlesVideo.setGeometry(QRect(860, 820, 411, 161))
        self.controlesVideo.setFrameShape(QFrame.Box)
        self.controlesVideo.setFrameShadow(QFrame.Raised)
        self.play = QPushButton(self.controlesVideo)
        self.play.setObjectName(u"play")
        self.play.setGeometry(QRect(20, 90, 75, 32))
        font1 = QFont()
        font1.setPointSize(14)
        self.play.setFont(font1)
        self.stop = QPushButton(self.controlesVideo)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(110, 90, 75, 32))
        self.stop.setFont(font1)
        self.pause = QPushButton(self.controlesVideo)
        self.pause.setObjectName(u"pause")
        self.pause.setGeometry(QRect(200, 90, 75, 32))
        self.pause.setFont(font1)
        self.loop = QCheckBox(self.controlesVideo)
        self.loop.setObjectName(u"loop")
        self.loop.setGeometry(QRect(300, 90, 70, 32))
        self.loop.setFont(font1)
        self.label_6 = QLabel(self.controlesVideo)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 10, 171, 30))
        self.label_6.setFont(font)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(420, 340, 401, 191))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setMidLineWidth(0)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 181, 30))
        self.label.setFont(font)
        self.vincularPorTiempo = QPushButton(self.frame)
        self.vincularPorTiempo.setObjectName(u"vincularPorTiempo")
        self.vincularPorTiempo.setGeometry(QRect(20, 50, 170, 32))
        self.vincularPorTiempo.setFont(font1)
        self.vincularPorEspacio = QPushButton(self.frame)
        self.vincularPorEspacio.setObjectName(u"vincularPorEspacio")
        self.vincularPorEspacio.setGeometry(QRect(210, 50, 170, 32))
        self.vincularPorEspacio.setFont(font1)
        self.desvincularTiempo = QPushButton(self.frame)
        self.desvincularTiempo.setObjectName(u"desvincularTiempo")
        self.desvincularTiempo.setGeometry(QRect(20, 140, 170, 32))
        self.desvincularTiempo.setFont(font1)
        self.hermanasDeTiempo = QLineEdit(self.frame)
        self.hermanasDeTiempo.setObjectName(u"hermanasDeTiempo")
        self.hermanasDeTiempo.setGeometry(QRect(20, 96, 170, 32))
        self.hermanasDeTiempo.setFont(font1)
        self.hermanasDeEspacio = QLineEdit(self.frame)
        self.hermanasDeEspacio.setObjectName(u"hermanasDeEspacio")
        self.hermanasDeEspacio.setGeometry(QRect(210, 96, 170, 32))
        self.hermanasDeEspacio.setFont(font1)
        self.desvincularEspacio = QPushButton(self.frame)
        self.desvincularEspacio.setObjectName(u"desvincularEspacio")
        self.desvincularEspacio.setGeometry(QRect(210, 140, 170, 32))
        self.desvincularEspacio.setFont(font1)
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(420, 130, 1351, 171))
        self.frame_3.setFrameShape(QFrame.Box)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 10, 91, 30))
        self.label_2.setFont(font)
        self.x1 = QPushButton(self.frame_3)
        self.x1.setObjectName(u"x1")
        self.x1.setGeometry(QRect(150, 10, 40, 32))
        self.x1.setFont(font1)
        self.x2 = QPushButton(self.frame_3)
        self.x2.setObjectName(u"x2")
        self.x2.setGeometry(QRect(200, 10, 40, 32))
        self.x2.setFont(font1)
        self.x3 = QPushButton(self.frame_3)
        self.x3.setObjectName(u"x3")
        self.x3.setGeometry(QRect(250, 10, 40, 32))
        self.x3.setFont(font1)
        self.x4 = QPushButton(self.frame_3)
        self.x4.setObjectName(u"x4")
        self.x4.setGeometry(QRect(300, 10, 40, 32))
        self.x4.setFont(font1)
        self.splitter_2 = QSplitter(self.frame_3)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(20, 60, 1311, 91))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.P1 = QPushButton(self.splitter_2)
        self.P1.setObjectName(u"P1")
        font2 = QFont()
        font2.setPointSize(15)
        self.P1.setFont(font2)
        self.P1.setCheckable(True)
        self.P1.setAutoExclusive(True)
        self.splitter_2.addWidget(self.P1)
        self.P2 = QPushButton(self.splitter_2)
        self.P2.setObjectName(u"P2")
        self.P2.setFont(font2)
        self.P2.setCheckable(True)
        self.P2.setAutoExclusive(True)
        self.splitter_2.addWidget(self.P2)
        self.P3 = QPushButton(self.splitter_2)
        self.P3.setObjectName(u"P3")
        self.P3.setFont(font2)
        self.P3.setCheckable(True)
        self.P3.setAutoExclusive(True)
        self.splitter_2.addWidget(self.P3)
        self.P4 = QPushButton(self.splitter_2)
        self.P4.setObjectName(u"P4")
        self.P4.setFont(font2)
        self.P4.setCheckable(True)
        self.P4.setAutoExclusive(True)
        self.splitter_2.addWidget(self.P4)
        self.P5 = QPushButton(self.splitter_2)
        self.P5.setObjectName(u"P5")
        self.P5.setFont(font2)
        self.P5.setCheckable(True)
        self.P5.setAutoExclusive(True)
        self.splitter_2.addWidget(self.P5)
        self.P6 = QPushButton(self.splitter_2)
        self.P6.setObjectName(u"P6")
        self.P6.setFont(font2)
        self.P6.setCheckable(True)
        self.P6.setAutoExclusive(True)
        self.splitter_2.addWidget(self.P6)
        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(860, 340, 411, 191))
        self.frame_4.setFrameShape(QFrame.Box)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.frame_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 10, 90, 30))
        self.label_3.setFont(font)
        self.addWeb = QPushButton(self.frame_4)
        self.addWeb.setObjectName(u"addWeb")
        self.addWeb.setGeometry(QRect(20, 140, 172, 32))
        self.addWeb.setFont(font1)
        self.addSerie = QPushButton(self.frame_4)
        self.addSerie.setObjectName(u"addSerie")
        self.addSerie.setGeometry(QRect(20, 50, 172, 32))
        self.addSerie.setFont(font1)
        self.addSerieWeb = QPushButton(self.frame_4)
        self.addSerieWeb.setObjectName(u"addSerieWeb")
        self.addSerieWeb.setGeometry(QRect(20, 96, 172, 32))
        self.addSerieWeb.setFont(font1)
        self.addVideo = QPushButton(self.frame_4)
        self.addVideo.setObjectName(u"addVideo")
        self.addVideo.setGeometry(QRect(220, 96, 172, 32))
        self.addVideo.setFont(font1)
        self.addImage = QPushButton(self.frame_4)
        self.addImage.setObjectName(u"addImage")
        self.addImage.setGeometry(QRect(220, 50, 172, 32))
        self.addImage.setFont(font1)
        self.frame_5 = QFrame(self.centralwidget)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(1310, 340, 461, 641))
        self.frame_5.setFrameShape(QFrame.Box)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.guardaPantallas = QPushButton(self.frame_5)
        self.guardaPantallas.setObjectName(u"guardaPantallas")
        self.guardaPantallas.setGeometry(QRect(300, 50, 141, 71))
        self.guardaPantallas.setFont(font1)
        self.listView = QListView(self.frame_5)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(20, 50, 261, 571))
        self.listView.setDragEnabled(True)
        self.listView.setDragDropOverwriteMode(False)
        self.listView.setDragDropMode(QAbstractItemView.InternalMove)
        self.listView.setAlternatingRowColors(True)
        self.listView.setMovement(QListView.Free)
        self.duplicar = QPushButton(self.frame_5)
        self.duplicar.setObjectName(u"duplicar")
        self.duplicar.setGeometry(QRect(300, 250, 141, 32))
        self.duplicar.setFont(font1)
        self.cargaGuion = QPushButton(self.frame_5)
        self.cargaGuion.setObjectName(u"cargaGuion")
        self.cargaGuion.setGeometry(QRect(300, 530, 141, 41))
        self.cargaGuion.setFont(font1)
        self.borrar = QPushButton(self.frame_5)
        self.borrar.setObjectName(u"borrar")
        self.borrar.setGeometry(QRect(300, 290, 141, 32))
        self.borrar.setFont(font1)
        self.playGuion = QPushButton(self.frame_5)
        self.playGuion.setObjectName(u"playGuion")
        self.playGuion.setGeometry(QRect(300, 330, 141, 32))
        self.playGuion.setFont(font1)
        self.stopGuion = QPushButton(self.frame_5)
        self.stopGuion.setObjectName(u"stopGuion")
        self.stopGuion.setGeometry(QRect(300, 370, 141, 32))
        self.stopGuion.setFont(font1)
        self.label_4 = QLabel(self.frame_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 61, 16))
        self.label_4.setFont(font)
        self.guardaGuion = QPushButton(self.frame_5)
        self.guardaGuion.setObjectName(u"guardaGuion")
        self.guardaGuion.setGeometry(QRect(300, 580, 141, 41))
        self.guardaGuion.setFont(font1)
        self.frame_6 = QFrame(self.centralwidget)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(420, 820, 401, 161))
        self.frame_6.setFrameShape(QFrame.Box)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.fpSlider = QSlider(self.frame_6)
        self.fpSlider.setObjectName(u"fpSlider")
        self.fpSlider.setGeometry(QRect(20, 50, 351, 29))
        self.fpSlider.setMinimum(10)
        self.fpSlider.setMaximum(20)
        self.fpSlider.setPageStep(3)
        self.fpSlider.setOrientation(Qt.Horizontal)
        self.frame_2 = QFrame(self.frame_6)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(20, 95, 351, 45))
        self.frame_2.setStyleSheet(u"background-color:lightgray")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.c5 = QLabel(self.frame_2)
        self.c5.setObjectName(u"c5")
        self.c5.setGeometry(QRect(270, 10, 64, 24))
        self.c5.setAutoFillBackground(False)
        self.c1 = QLabel(self.frame_2)
        self.c1.setObjectName(u"c1")
        self.c1.setGeometry(QRect(14, 10, 64, 24))
        self.c1.setAutoFillBackground(False)
        self.c2 = QLabel(self.frame_2)
        self.c2.setObjectName(u"c2")
        self.c2.setGeometry(QRect(78, 10, 64, 24))
        self.c2.setAutoFillBackground(False)
        self.c3 = QLabel(self.frame_2)
        self.c3.setObjectName(u"c3")
        self.c3.setGeometry(QRect(142, 10, 64, 24))
        self.c3.setAutoFillBackground(False)
        self.c4 = QLabel(self.frame_2)
        self.c4.setObjectName(u"c4")
        self.c4.setGeometry(QRect(206, 10, 64, 24))
        self.c4.setAutoFillBackground(False)
        self.label_5 = QLabel(self.frame_6)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 10, 121, 30))
        self.label_5.setFont(font)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(420, 30, 1351, 71))
        font3 = QFont()
        font3.setPointSize(32)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"color: rgb(3, 78, 168);")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.frame_7 = QFrame(self.centralwidget)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(90, 40, 231, 941))
        self.frame_7.setAutoFillBackground(False)
        self.frame_7.setFrameShape(QFrame.Box)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.logos = QLabel(self.frame_7)
        self.logos.setObjectName(u"logos")
        self.logos.setGeometry(QRect(60, 0, 121, 941))
        self.satellite = QPushButton(self.centralwidget)
        self.satellite.setObjectName(u"satellite")
        self.satellite.setGeometry(QRect(590, 550, 75, 23))
        self.calles = QPushButton(self.centralwidget)
        self.calles.setObjectName(u"calles")
        self.calles.setGeometry(QRect(680, 550, 75, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1900, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tablero de control", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Tiempo", None))
        self.play.setText(QCoreApplication.translate("MainWindow", u"Play", None))
        self.stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.pause.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.loop.setText(QCoreApplication.translate("MainWindow", u"Loop", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Control de video", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Vincular pantallas:", None))
        self.vincularPorTiempo.setText(QCoreApplication.translate("MainWindow", u"Por tiempo", None))
        self.vincularPorEspacio.setText(QCoreApplication.translate("MainWindow", u"Por espacio", None))
        self.desvincularTiempo.setText(QCoreApplication.translate("MainWindow", u"Desvincular", None))
        self.desvincularEspacio.setText(QCoreApplication.translate("MainWindow", u"Desvincular", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Pantallas", None))
        self.x1.setText(QCoreApplication.translate("MainWindow", u"x1", None))
        self.x2.setText(QCoreApplication.translate("MainWindow", u"x2", None))
        self.x3.setText(QCoreApplication.translate("MainWindow", u"x3", None))
        self.x4.setText(QCoreApplication.translate("MainWindow", u"x4", None))
        self.P1.setText(QCoreApplication.translate("MainWindow", u"P1", None))
        self.P2.setText(QCoreApplication.translate("MainWindow", u"P2", None))
        self.P3.setText(QCoreApplication.translate("MainWindow", u"P3", None))
        self.P4.setText(QCoreApplication.translate("MainWindow", u"P4", None))
        self.P5.setText(QCoreApplication.translate("MainWindow", u"P5", None))
        self.P6.setText(QCoreApplication.translate("MainWindow", u"P6", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Agregar:", None))
        self.addWeb.setText(QCoreApplication.translate("MainWindow", u"P\u00e1gina web", None))
        self.addSerie.setText(QCoreApplication.translate("MainWindow", u"Serie de im\u00e1genes", None))
        self.addSerieWeb.setText(QCoreApplication.translate("MainWindow", u"Serie web", None))
        self.addVideo.setText(QCoreApplication.translate("MainWindow", u"Video", None))
        self.addImage.setText(QCoreApplication.translate("MainWindow", u" Imagen", None))
        self.guardaPantallas.setText(QCoreApplication.translate("MainWindow", u"Guarda \n"
"pantallas", None))
        self.duplicar.setText(QCoreApplication.translate("MainWindow", u"Duplicar", None))
        self.cargaGuion.setText(QCoreApplication.translate("MainWindow", u"Carga Gui\u00f3n", None))
        self.borrar.setText(QCoreApplication.translate("MainWindow", u"Borrar", None))
        self.playGuion.setText(QCoreApplication.translate("MainWindow", u"Play", None))
        self.stopGuion.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Gui\u00f3n", None))
        self.guardaGuion.setText(QCoreApplication.translate("MainWindow", u"Guarda Gui\u00f3n", None))
        self.c5.setText("")
        self.c1.setText("")
        self.c2.setText("")
        self.c3.setText("")
        self.c4.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Categor\u00edas", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Plataforma para visualizaci\u00f3n en salas de inmersi\u00f3n", None))
        self.logos.setText("")
        self.satellite.setText(QCoreApplication.translate("MainWindow", u"Satellite", None))
        self.calles.setText(QCoreApplication.translate("MainWindow", u"Calles", None))
    # retranslateUi

